alert_information/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stocks.urls'))
]

stocks/urls.py
from django.urls import path
from .views import StockView, AddStocks, HomeView, OrderStock, add_stock

app_name = "stocks"

urlpatterns = [
    path('stocks/', StockView.as_view(), name='stocks'),
    path('order-stocks/', OrderStock.as_view(), name='order'),
    path('add-stocks/', add_stock, name='add'),
    path('', HomeView.as_view(), name='home'),
]

stocks/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=25, null=False, default='paracetamol')
    quantity = models.PositiveIntegerField(null=False)
    min_stock = models.PositiveBigIntegerField(default=100)
    cost_price = models.PositiveIntegerField(default=3500)
    selling_price = models.PositiveIntegerField(default=4000)

    def __str__(self):
        return self.name

stocks/forms.py
from django import forms

class StockForm(forms.Form):
    checkbox = forms.MultipleChoiceField(required=True, widget=forms.CheckboxSelectMultiple, 
                                         choices=[
            ('panadol', 'panadol'), ('paracetamol', 'paracetamol'),
            ('panadol xtra', 'panadol xtra'), ('procold', 'procold'), ('vitamin c', 'vitamin C'),
        ])
    quantity = forms.IntegerField(required=True)
    cost_price = forms.IntegerField(required=True)
    selling_price = forms.IntegerField(required=True)

stocks/views.py
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic import TemplateView, ListView
from django.contrib import messages
from django.forms.models import BaseModelForm
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from .models import Product
from .forms import StockForm
# Create your views here.

def add_stock(request):
    if request.method == "GET":
        v = {
            'quantity': 100,
            'cost_price': 3500,
            'selling_price': 4000
        }
        form = StockForm(v)
    if request.method == "POST":
        form = StockForm(request.POST)
        if form.is_valid():
            drug = form.cleaned_data.get('checkbox')
            for d in drug:
                p = Product.objects.filter(name=d).first()
                if p:
                    p.quantity += form.cleaned_data.get('quantity')
                    p.cost_price = form.cleaned_data.get('cost_price')
                    p.selling_price = form.cleaned_data.get('selling_price')
                    print(p.quantity)
                    p.save()
            messages.info(request, "Stocks have been successfully added to inventory!")
            return redirect(reverse('stocks:stocks'))
    return render(request, 'add-stocks.html', {"form":form})

class HomeView(TemplateView):
    template_name = "home.html"

class OrderStock(TemplateView):
    template_name = "order-stocks.html"

    def post(self, request):
        messages.info(request, "Your order have been submitted successfully!")
        return redirect(reverse('stocks:order'))

class AddStocks(CreateView):
    template_name = "add-stocks.html"
    model = Product
    success_url = '/add-stocks/'
    fields = ['quantity', 'cost_price', 'selling_price']

    def post(self, request, kwargs):
        self.pk = kwargs.get('pk')
        return super().post(request, kwargs)

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.quantity += Product.objects.get(self.pk_url_kwarg).first().quantity
        return super().form_valid(form)

class StockView(ListView):
    template_name = "stocks.html"
    model = Product

templates/add-stocks.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playpen+Sans&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ALERT BASED INVENTORY APPLICATION</title>
    <link rel="stylesheet" href="{% static 'style-1.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

</head>

<body style="overflow:auto !important; margin: 0; padding: 0;">

    <section class="form">
        <div class="forms">
            {% if messages %}
                {% for message in messages %}
                    <p class="{{message.tags}}">{{message.message}}</p>
                {% endfor %}
            {% endif %}
            <h1>Add stocks</h1>
            <div class="form-input">
                <form action="#" class="input check" method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <div class="btn">
                        <input type="submit" value="Add Stocks" />
                    </div>
                </form>
            </div>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa"
        crossorigin="anonymous"></script>
</body>

</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playpen+Sans&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ALERT BASED INVENTORY APPLICATION</title>
    <link rel="stylesheet" href="{% static 'style-1.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo&family=Playpen+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

</head>

<body>
    <section class="home">
        <div class="home-page">
            <div class="home-page-header">
                <nav class="navbar navbar-expand-lg">
                    <div class="container-fluid">
                        <a class="navbar-brand" href="/home.html">
                            <h1>Fsars Medical</h1>
                        </a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navigators">
                            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                    <li class="nav-item">
                                        <a class="nav-link" href="/home.html">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#service">services</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#testimony">testimonials</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'stocks:stocks'%}">inventory</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'stocks:order'%}">Order stocks</a>
                                    </li>
                                </ul>
                                <a href="{% url 'stocks:add'%}"><button>add stocks</button></a>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
            <div class="home-content">
                <h1>alert based inventory application</h1>
                <p>health innovation technology.</p>
                <a href=""><button>read more</button></a>
            </div>
        </div>
    </section>

    <section class="service" id="service">
        <div class="services">
            <div class="box">
                <i class="fa fa-hospital fa-shake"></i>
                <h3>get diagnostic report</h3>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorem error ullam quos maiores fugiat.
                    reprehenderit suscipit deleniti quos!</p>
                <button>read more</button>
            </div>
            <div class="box">
                <i class="fa fa-user-doctor fa-spin"></i>
                <h3>help by specialist</h3>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorem error ullam quos maiores fugiat.
                    reprehenderit suscipit deleniti quos!</p>
                <button>read more</button>
            </div>
            <div class="box">
                <i class="fa fa-calendar fa-beat-fade"></i>
                <h3>choose your package</h3>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorem error ullam quos maiores fugiat.
                    reprehenderit suscipit deleniti quos!</p>
                <button>read more</button>
            </div>
            <div class="box  box-design">
                <i class="fa fa-check fa-beat"></i>
                <h3>make appointments</h3>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorem error ullam quos maiores fugiat.
                    reprehenderit suscipit deleniti quos!</p>
                <button>read more</button>
            </div>
        </div>
    </section>

    <section class="testimony" id="testimony">
        <div class="testimonies">
            <div class="testimonials">
                <h3>testimonials</h3>
                <img src="/static/img/person.webp" alt="person">
                <p class="name">JONATHAN MATHEW</p>
                <p><span>"</span>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias nam harum, soluta
                    facilis, labor ratione ab dolor exercitationem id odio laboriosam similique consectetur, voluptatum
                    iure
                    <span>"</span>
                </p>
            </div>
        </div>
    </section>

    <section class="order stocks">
        <div class="order stock">
            <div class="order">
                <h3>order for more stocks</h3>
                <p>Welcome to fsars medical, where legit drrugs are giagnosed to individuals for their safety
                    and also for good healths. please the order button to order for more stocks and if stocks are
                    available please
                    click the add stocks button to add more stocks.
                </p>
                <a href="{% url 'stocks:order'%}"> <button>order stocks</button></a>
                <a href="{% url 'stocks:add'%}"><button>add stocks</button></a>
            </div>
        </div>
    </section>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa"
        crossorigin="anonymous"></script>
</body>

</html>

templates/order-stocks.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playpen+Sans&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ALERT BASED INVENTORY APPLICATION</title>
    <link rel="stylesheet" href="{% static 'style-1.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

</head>

<body style="overflow: hidden; margin: 0; padding: 0;">

    <section class="form formm">
        <div class="forms">
            {% if messages %}
            {% for message in messages %}
            <p class="{{message.tags}}">{{message.message}}</p>
            {% endfor %}
            {% endif %}
            <h1>order stocks</h1>
            <div class="form-checked">
                <form action="" class="check">
                    <h4>select products to order:</h4>
                    <input type="checkbox" id="product1" name="product1" value="panadol">
                    <label for="checkbox">panadol</label> <br>
                    <input type="checkbox" id="product1" name="product2" value="paracetamol">
                    <label for="checkbox">paracetamol</label>
                    <input type="checkbox" id="product1" name="product3" value="panadol xtra">
                    <label for="checkbox">panadol xtra</label> <br>
                    <input type="checkbox" id="product1" name="product4" value="vitamin C">
                    <label for="checkbox">vitamin C</label>
                    <input type="checkbox" id="product1" name="product5" value="procold">
                    <label for="checkbox">procold</label>
                </form>
            </div>
            <div class="form-input">
                <form action="#" class="input" method="post">
                    {% csrf_token %}
                    <h4>quantity:</h4>
                    <input type="text" name="qty">
                    <h4>totol cost price:</h4>
                    <input type="text" name="qty" placeholder="cost price in naira">
                    <div class="buttons">

                        <button type="submit">Order</button></a>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa"
        crossorigin="anonymous"></script>
</body>

</html>

templates/stocks.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playpen+Sans&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ALERT BASED INVENTORY APPLICATION</title>
    <link rel="stylesheet" href="{% static 'style-1.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

</head>

<body style="margin: 0; padding: 0;">

    <section class="form formmm">
        <div class="forms">
            <h1>stocks available</h1>
            <div class="form-input">
                {% if messages %}
                {% for message in messages %}
                <p class="{{message.tags}}">{{message.message}}</p>
                {% endfor %}
                {% endif %}
                <h3>list of stocks available:</h3>
                {% for pro in object_list %}
                <form action="" class="input">
                    {% if pro.quantity < pro.min_stock%} <p class="error">Stock level for "{{pro.name}}" is low, add
                        stocks
                        or order for more stocks.</p>
                        {% endif %}
                        <ul>
                            <li>product: {{pro.name}}</li>
                            <li>quantities: {{pro.quantity}}</li>
                            <li>cost price per each: {{pro.cost_price}}</li>
                            <li>selling price per each: {{pro.selling_price}}</li>
                            <li>minimum stock level: {{pro.min_stock}}</li>
                        </ul>
                </form>
                <hr />
                {% endfor%}
            </div>
            <div class="buttons">
                <a href="{% url 'stocks:add'%}"><button>Add Stocks</button></a>
                <a href="{% url 'stocks:order'%}"><button>order stocks</button></a>
            </div>
            <p><a href="/">go back to home page</a></p>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa"
        crossorigin="anonymous"></script>
</body>

</html>